# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fenrir.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fenrir.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x65nrir.proto\x12\x0c\x66\x65nrirMandou\"\x87\x01\n\x06Tarefa\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12+\n\x06status\x18\x04 \x01(\x0e\x32\x1b.fenrirMandou.Status_Tarefa\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\t\x12\x13\n\x0bresponsavel\x18\x06 \x03(\t\"T\n\x0c\x43riarRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x13\n\x0bresponsavel\x18\x04 \x03(\t\"\x0f\n\rListarRequest\"7\n\x0eListarResponse\x12%\n\x07tarefas\x18\x01 \x03(\x0b\x32\x14.fenrirMandou.Tarefa\"\x1c\n\x0e\x44\x65letarRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x0f\x44\x65letarResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t*>\n\rStatus_Tarefa\x12\x0c\n\x08PENDENTE\x10\x00\x12\x10\n\x0c\x45M_ANDAMENTO\x10\x01\x12\r\n\tCONCLUIDA\x10\x02\x32\x9d\x02\n\x12GerenciadorTarefas\x12;\n\x05\x43riar\x12\x1a.fenrirMandou.CriarRequest\x1a\x14.fenrirMandou.Tarefa\"\x00\x12\x45\n\x06Listar\x12\x1b.fenrirMandou.ListarRequest\x1a\x1c.fenrirMandou.ListarResponse\"\x00\x12\x39\n\tAtualizar\x12\x14.fenrirMandou.Tarefa\x1a\x14.fenrirMandou.Tarefa\"\x00\x12H\n\x07\x44\x65letar\x12\x1c.fenrirMandou.DeletarRequest\x1a\x1d.fenrirMandou.DeletarResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fenrir_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUS_TAREFA']._serialized_start=395
  _globals['_STATUS_TAREFA']._serialized_end=457
  _globals['_TAREFA']._serialized_start=31
  _globals['_TAREFA']._serialized_end=166
  _globals['_CRIARREQUEST']._serialized_start=168
  _globals['_CRIARREQUEST']._serialized_end=252
  _globals['_LISTARREQUEST']._serialized_start=254
  _globals['_LISTARREQUEST']._serialized_end=269
  _globals['_LISTARRESPONSE']._serialized_start=271
  _globals['_LISTARRESPONSE']._serialized_end=326
  _globals['_DELETARREQUEST']._serialized_start=328
  _globals['_DELETARREQUEST']._serialized_end=356
  _globals['_DELETARRESPONSE']._serialized_start=358
  _globals['_DELETARRESPONSE']._serialized_end=393
  _globals['_GERENCIADORTAREFAS']._serialized_start=460
  _globals['_GERENCIADORTAREFAS']._serialized_end=745
# @@protoc_insertion_point(module_scope)
